# NumPy is a linerar algebra library for python

In [1]:
import numpy as np

In [3]:
mylist = [i for i in range(10)]
type(mylist)

list

In [4]:
mylist*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
myarray = np.array(mylist)
type(myarray)

numpy.ndarray

In [6]:
myarray*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
mymatrix = np.array([[0,1,5],[-2,1,4],[76,8,9]])
mymatrix

array([[ 0,  1,  5],
       [-2,  1,  4],
       [76,  8,  9]])

In [11]:
# first row
mymatrix[:,0:1]

array([[ 0],
       [-2],
       [76]])

In [12]:
# middle row
mymatrix[0:3,1:2]

array([[1],
       [1],
       [8]])

In [13]:
mymatrix[0:2,2:3]

array([[5],
       [4]])

In [15]:
# whole matrix 
mymatrix[:,:]

array([[ 0,  1,  5],
       [-2,  1,  4],
       [76,  8,  9]])

In [16]:
# whole matrix
mymatrix[0:3,0:3]

array([[ 0,  1,  5],
       [-2,  1,  4],
       [76,  8,  9]])

## Built-in Methods

* ## arrange
    * return evenly spaced values within a given interval
    

In [18]:
myarange = np.arange(10)
myarange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
myrangestep = np.arange(0,10,2)
myrangestep

array([0, 2, 4, 6, 8])

# zeros and ones
* ### generate arrays of zeros or ones

In [22]:
Z = np.zeros(4)
Z

array([0., 0., 0., 0.])

In [23]:
Z3 = np.zeros((3,3))
Z3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
O1 = np.ones(5)
O1

array([1., 1., 1., 1., 1.])

In [26]:
O6 = np.ones((6,6))
O6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# linspace
* ### return evenly spaced numbers over a specified interval

In [30]:
L = np.linspace(1,25,9)
L

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [31]:
L3 = L.reshape(3,3)
L3

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

# eye
* ### creates an identity matrix

In [34]:
I4 = np.eye(4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
I2 = np.eye(2)
I2

array([[1., 0.],
       [0., 1.]])

In [37]:
I43 = np.eye(4,3)
I43

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [39]:
# select rows and columns 1&2
I43[0:2,0:2]

array([[1., 0.],
       [0., 1.]])

# random
* ### numpy also has lots of ways to create random number arrays

In [40]:
import random

In [41]:
arr = np.random.rand(3,4)
arr

array([[0.84041664, 0.21342139, 0.44234487, 0.55426746],
       [0.46765039, 0.70337306, 0.03566949, 0.51123303],
       [0.74360559, 0.1776259 , 0.64083215, 0.07164692]])

In [42]:
from numpy.random import rand

In [44]:
arr_simple = rand(3,4)
arr_simple

array([[0.74640527, 0.2941211 , 0.10683995, 0.9390282 ],
       [0.56988779, 0.23102051, 0.62814895, 0.91957606],
       [0.42423721, 0.70665683, 0.4556918 , 0.53821036]])

# randn
* ### return a sample(s) from the standard normal distribution. unlike rand which is uniform

In [45]:
from numpy.random import randn

In [46]:
mat = randn(3,2)
mat

array([[-1.50628604,  0.44814306],
       [ 0.40584051,  0.1647221 ],
       [-1.51482241,  0.9041686 ]])